# Runs every 10 minutes (or manual) to fetch CSVs and commit data/*.json into the repo.
name: update-data
on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:

jobs:
  build-and-commit-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # so the built-in GITHUB_TOKEN can push
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run data fetch script
        run: |
          python scripts/fetch_data.py
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          if git diff --cached --quiet; then
            echo "No data changes to commit"
          else
            git commit -m "chore(data): update cached CSV JSONs [skip ci]"
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
